# -*- coding: utf-8 -*-

import logging

from openode.const import (
    NODE_USER_ROLE_MEMBER,
    NODE_USER_ROLE_MANAGER
    )
from openode.models.node import Node

################################################################################

MEMBERS = {
    "ikudrnacova@kr-kralovehradecky.cz": [30],
    "jkosarzova@seznam.cz": [29],
    "jelinek.jj@gmail.com": [29],
    "zuzana.janeckova@mpsv.cz": [25],
    "ivana.budkova@mpsv.cz": [25],
    "katerina.licmanova@mpsv.cz": [25],
    "martinahajna@seznam.cz": [39, 34, 23, 29],
    "jiri.bradac@mpsv.cz": [39],
    "buchtova@nvf.cz": [22],
    "svoboda@nvf.cz": [22],
    "stetkova@nvf.cz": [22],
    "tomas.hobza@mpsv.cz": [21, 27, 25, 28],
    "kalaskova@aqe.cz": [47],
    "vera.jiraskova@mpsv.cz": [25],
    "lucka.hrom@centrum.cz": [27, 25, 28],
    "petra.ulrichova@mpsv.cz": [25],
    "matus.sucha@upol.cz": [29],
    "keris@centrum.cz": [30],
    "juroskova@businesslink.cz": [29],
    "petr.holan@email.cz": [29],
    "oldrich.gemrot@gmail.com": [34, 23, 29],
    "jiri.chasak@post.cz": [29],
    "jana.souchova@cb.mpsv.cz": [27, 25, 28],
    "malkova@stapro.cz": [29],
    "sylva.sladeckova@seznam.cz": [29],
    "adela.purschova@mpsv.cz": [50, 25, 29, 28],
    "roldanova.z@seznam.cz": [29, 29],
    "alena.bielakova@pa.mpsv.cz": [27, 28],
    "michala.trlicikova@mpsv.cz": [25],
    "zdenka.plavjanikova@mpsv.cz": [39],
    "gabriela.kankova@mpsv.cz": [39],
    "snopkova@ceskyprojekt.cz": [29],
    "ronzova@rycon.cz": [29],
    "petra.novotna@mpsv.cz": [25, 38, 28],
    "hana.erlebachova@chc.cz": [29],
    "lenka.bilkova@mpsv.cz": [25],
    "igor.hruza@mpsv.cz": [39],
    "marat.saber@mvcr.cz": [25],
    "gabriela.merinska@mpsv.cz": [25, 29],
    "jana.knizova@mpsv.cz": [25],
    "pavlina.tosnerova@mpsv.cz": [25, 35],
    "hynek.kalvoda@obcanskeporadny.cz": [51, 29],
    "magdacernicka@muzlin.cz": [29],
    "zezulak@ohkuh.cz": [29],
    "stepanka.sykorova@mvcr.cz": [25],
    "necasova@nvf.cz": [22],
    "lucie.voseckova@gmail.com": [51, 34, 29, 29, 29],
    "juptner.ivan@seznam.cz": [33],
    "schanel@zhkhk.cz": [29],
    "soukup@asistencnicentrum.cz": [29],
    "r.butora@educocentrum.cz": [29],
    "lucie.truneckova@mpsv.cz": [21],
    "stanislav.safar@seznam.cz": [29],
    "p.zemanek96@email.cz": [29],
    "kohout@mpo.cz": [25],
    "svatava.skantova@mpsv.cz": [25],
    "noemir@seznam.cz": [31, 25],
    "irena.peterkova@seznam.cz": [21, 27, 25],
    "zuzana.hradecka@mvcr.cz": [25],
    "anna.suhajova@mpsv.cz": [21, 25],
    "ivana.haladova@crossczech.cz": [29],
    "vosmerova@aqe.cz": [47],
    "tomas.chovanec@cpkp.cz": [51, 29],
    "k.brabcova@zahrada2000.cz": [33],
    "marz134@seznam.cz": [34, 29],
    "karel.myska@uhk.cz": [29],
    "pavel.kalina@mpsv.cz": [25, 35],
    "lucie.michaniklova@mpsv.cz": [25, 38, 28],
    "marcel.mares@mpsv.cz": [25],
    "opelechova@ostrava.cz": [29],
    "jarmila.tomancova@seznam.cz": [34, 29],
    "lukas.muller@mpsv.cz": [25],
    "maly@pef.czu.cz": [29],
    "jakub.skoda@mpsv.cz": [39, 25, 38],
    "alzbeta.cerna1@mpsv.cz": [39, 25],
    "hana.hamernikova@mpsv.cz": [39],
    "magdalena.sikorova@profaktum.cz": [29],
    "sapesner@autosap.cz": [30],
    "pell@seznam.cz": [23, 29, 29],
    "kristyna.radostova@mvcr.cz": [25],
    "helena.hofrajtrova@mpsv.cz": [25],
    "zlutytulipan@centrum.cz": [51, 20, 29],
    "barbora.machova@mpsv.cz": [25],
    "marketa.pouzarova@mpsv.cz": [50, 25, 29],
    "katerina.saskova@mpsv.cz": [27, 25, 28],
    "miluse.hnojska@mpsv.cz": [25, 38, 28],
    "beresova@vcvscr.cz": [29, 29],
    "foxy017@gmail.com": [29],
    "hana.ruzanska@volny.cz": [23, 29],
    "jana.chlumska@mpsv.cz": [25, 38],
    "ortovah@skolalipa.cz": [29],
    "nada.novotna@mpsv.cz": [25],
    "gazdagova@centrum.cz": [23, 29],
    "tatana.vencovska@gmail.com": [29],
    "barbara.vavrova@mpsv.cz": [38],
    "jana.bartonova@mpsv.cz": [25, 32],
    "monika.barnetova@mpsv.cz": [21, 25, 28],
    "dana.krouzelova@mvcr.cz": [25],
    "dobsik.ludek@creditactivity.info": [29],
    "hadravova.j@kr-vysocina.cz": [30],
    "pavel.kajml@uzs.cz": [29],
    "ivana.prihonska@mpsv.cz": [25],
    "petra.drahonovska@gmail.com": [29],
    "filip.kucera@mpsv.cz": [24, 25, 38],
    "iva.ciglbauerova@mpsv.cz": [50, 39, 25, 38, 29],
    "zita.nidlova@seznam.cz": [29],
    "danawai@post.cz": [29],
    "kristyna.dreisigova@mo.mpsv.cz": [27, 25, 28],
    "martinek.dusan@cmkos.cz": [24],
    "alena.holikova@mvcr.cz": [25, 38],
    "vodnanska@meta-os.cz": [23, 29, 29],
    "michal.holy@jn.mpsv.cz": [34, 23, 29],
    "tomas.gresek@eduway.cz": [23],
    "flusserova@nvf.cz": [22],
    "hola.pt@seznam.cz": [29],
    "katarina.berounova@mpsv.cz": [25],
    "martina.sovjakova@mpsv.cz": [39, 25],
    "vhrcek@seznam.cz": [29],
    "ryclova@qqt.cz": [31],
    "lukas.hrabak@mpsv.cz": [25],
    "petr.belohrad@mpsv.cz": [25],
    "veronika.mrmusova@email.cz": [29],
    "petra.vorlikova@mvcr.cz": [25, 38],
    "jiri.pilar@adminmz.cz": [31],
    "svagerka@ohkhodonin.cz": [29],
    "nadezda.krohova@seznam.cz": [23, 29],
    "ivan.kopriva@mpsv.cz": [25],
    "vandeelenova@scmvd.cz": [24],
    "jarolimek@pef.czu.cz": [29],
    "pavel.stafek@aisis.cz": [29],
    "dankub@email.cz": [39],
    "zieglerova.a@seznam.cz": [23, 29],
    "vera.palowska@cityofprague.cz": [31, 25, 28],
    "helena.stoklasova@mo.mpsv.cz": [27, 25, 28],
    "lada.vyhnankova@mpsv.cz": [25],
    "eva.vankova@mpsv.cz": [25],
    "jindra.dienstbierova@fdv.mpsv.cz": [39],
    "francova@ckpul.cz": [33],
    "jan.baroch@mvcr.cz": [25],
    "michaela.neubertova@mpsv.cz": [25],
    "korselt@centrum.cz": [29],
    "gabriela@drastich.com": [23, 29],
    "vladimir@tauer.info": [29],
    "jan.zeman@mvcr.cz": [25, 38],
    "irena.duskova@volny.cz": [23, 29],
    "anna.ficova@mpsv.cz": [25],
    "eduard.hromada@fsv.cvut.cz": [29],
    "alice.bezouskova@gmail.com": [51, 29],
    "petr.vitouch@inc.cz": [29],
    "m.vokrinkova@seznam.cz": [23, 29],
    "matej.mraz@mpsv.cz": [25],
    "anna.vachova@mpsv.cz": [25],
    "rzivna@seznam.cz": [32, 29],
    "filip.kubik@mpsv.cz": [25],
    "projekty@grafia.cz": [29],
    "michaela.navratilova@mpsv.cz": [39],
    "adela.pilarova@mvcr.cz": [25],
    "michaela.kloudova@qqt.cz": [31],
    "kustan@tiscali.cz": [29],
    "lsazimova@gmail.com": [51, 34, 29],
    "dusan.nemec@mpsv.cz": [25, 28],
    "sipi@email.cz": [34, 29],
    "ivana.tluchorova@mpsv.cz": [25],
    "jirina.capova@mpsv.cz": [39, 25],
    "jana.frendlovska@mvcr.cz": [25],
    "jirina.bukovska@mpsv.cz": [25],
    "martin.smidl@mpsv.cz": [27, 25, 28],
    "katerina.zivotska@mpsv.cz": [21, 27, 25],
    "h.skornokova@seznam.cz": [34, 29, 49],
    "andrea.urbanova@mpsv.cz": [25],
    "s.turek@zahrada2000.cz": [33],
    "barbora.dostalova@suip.cz": [39],
    "jitka.svitakova@mpsv.cz": [21, 39, 25],
    "ladislav.kolarik@mvcr.cz": [25],
    "daniel.heidler@gmail.com": [29],
    "anna.burjankova@mpsv.cz": [25],
    "petr.valasek@kr-zlinsky.cz": [30],
    "evazilay@centrum.cz": [29],
    "david.benak@gmail.com": [34, 29],
    "ivo.ptacnik@centrum.cz": [29],
    "kristyna.tkadlecova@mpsv.cz": [25],
    "vladimir.vasinek@vsb.cz": [29],
    "rplischkova@email.cz": [29],
    "blanka.v@seznam.cz": [51, 34, 29],
    "marek.simak@mpsv.cz": [25],
    "leonahozova@seznam.cz": [29],
    "berankova@pef.czu.cz": [29, 29],
    "iva.kocianova@mvcr.cz": [25],
    "jirina.svitakova@mpsv.cz": [25],
    "jana.novotna@mpsv.cz": [39],
    "jana.kralovianska@mvcr.cz": [25],
    "vera.galuszkova@mvcr.cz": [25, 38],
    "hana.novakova@projectconsulting.cz": [30],
    "dockalova@nvf.cz": [22],
    "jan.zavadil@mvcr.cz": [38],
    "jana.stollova@seznam.cz": [51, 34, 23, 29],
    "e.lici@seznam.cz": [22, 32],
    "pnovak@mvcr.cz": [24],
    "erika.safrankova@mpsv.cz": [27, 25, 28],
    "kriz@kmm.zcu.cz": [29],
    "kacarovova@seznam.cz": [29],
    "nada.krupczova@seznam.cz": [29],
    "fidlerova@nvf.cz": [29],
    "hana.wirthova@suip.cz": [39],
    "roman.benes@mvcr.cz": [25],
    "organizace@nakrizovatcevdf.eu": [20, 34, 23, 29],
    "jaroslava.b.sporkova@gmail.com": [23, 29],
    "tomko.lukas@seznam.cz": [29],
    "mail.jana@centrum.cz": [51, 34, 29],
    "janpistek@atlas.cz": [34, 23, 29],
    "uhlir@rodos94.cz": [29],
    "jana.vavrova@mvcr.cz": [21, 25],
    "nekola@fsv.cuni.cz": [29],
    "martin@edukol.cz": [29, 29],
    "milan.masnica@mpsv.cz": [25],
    "adam.severyn@mpsv.cz": [39, 25, 28, 30],
    "ulehlova@spondea.cz": [29],
    "voiitason@seznam.cz": [38],
    "nerud@volny.cz": [51, 34, 29, 49],
    "marketa.tvrzska@mpsv.cz": [39],
    "kroh@europoradenstvi.cz": [29],
    "martina.kunova@czechinvest.org": [25],
    "lenka.truneckova@fdv.mpsv.cz": [39],
    "doleckova@aqe.cz": [47],
    "jirina.kraifova@gmail.com": [29],
    "jiri.neuberg@mpsv.cz": [50, 25, 38, 29],
    "mona-s@seznam.cz": [29],
    "michal.povolny@mvcr.cz": [25],
    "zdenek.klouda@gmail.com": [29],
    "ryliska@centrum.cz": [31],
    "martinaby@seznam.cz": [34, 23, 29],
    "tomas.fantys@cb.mpsv.cz": [27, 25, 28],
    "kstrachonova@centrum.cz": [34, 23, 29],
    "aneta.slukova@fdv.mpsv.cz": [39],
    "ivana.vostra@fdv.mpsv.cz": [39],
    "katerina.tylova@vfn.cz": [22, 32, 34, 23, 29],
    "t.jelinek@cityofprague.cz": [35],
    "fencl@mpo.cz": [25],
    "jaromira.kotikova@vupsv.cz": [29],
    "marketa.charvatova@mpsv.cz": [39, 25, 38],
    "jana.urbankova@mpsv.cz": [25],
    "jan.cerny@clovekvtisni.cz": [33],
    "kristina.prejdova@mpsv.cz": [39],
    "brezinova@nvf.cz": [22],
    "hana.krbeckova@mvcr.cz": [25],
    "tereza.cechova@mo.mpsv.cz": [27, 28],
    "radek.mach@apis-nb.cz": [29, 30],
    "kasikova@nvf.cz": [22],
    "vera.nouzova@mpsv.cz": [21, 25, 28],
    "podpora34-51@ea-oplzz.cz": [25, 29, 29, 28],
    "jana_sobeslavska@env.cz": [24],
    "sarka.mullerova@mpsv.cz": [25, 38],
    "vojackova@rect.muni.cz": [29],
    "eva.matulova@mvcr.cz": [25, 38],
    "j.mann@selex.cz": [29],
    "petr.korecky@mpsv.cz": [24, 25],
    "martina.cuprova@mpsv.cz": [27, 25, 28],
    "dhconsulting@seznam.cz": [29],
    "m.gajdusek@kr-olomoucky.cz": [35],
    "katerina.murlova@mpsv.cz": [36, 25, 28],
    "eva.touskova@bm.mpsv.cz": [29],
    "magda.podsednik@gmail.com": [29],
    "baxova@gmail.com": [51, 34, 23, 29],
    "helena.vojtaskova@mpsv.cz": [25],
    "marketa.cedikova@czechinvest.org": [25],
    "tomas.travnicek@mpsv.cz": [39, 25],
    "veronika.fialkova@cz.ey.com": [25],
    "helena.liskova@mpsv.cz": [25],
    "achvojkova@spcr.cz": [24],
    "pavlina.cechova@mpsv.cz": [25],
    "fadrhons@centrum.cz": [29],
    "tomas.zmeskal@email.cz": [29],
    "petr.valek@mpsv.cz": [25, 38],
    "ozorovska@seznam.cz": [29],
    "jitka.prokopiusova@mpsv.cz": [25, 38],
    "pavlina.mildnerova@seznam.cz": [22],
    "vladimir.doucek@mmr.cz": [24],
    "eva.sikorova@mpsv.cz": [34, 23, 29],
    "jitka@obcan.org": [34, 23, 29],
    "famerovar@email.cz": [34, 29, 29],
    "machjiri1@gmail.com": [29],
    "chobix@seznam.cz": [22],
    "hana.solarova@seznam.cz": [51, 23, 29, 29],
    "marcel.adam@zl.mpsv.cz": [29],
    "eva.svobodova@mpsv.cz": [25, 38],
    "stejskai@fm.vse.cz": [29],
    "olga.stanickova@seznam.cz": [29],
    "labyrint-brno@volny.cz": [29],
    "jitkadarmovzalova@centrum.cz": [34, 29],
    "katerina.krizova@fdv.mpsv.cz": [39],
    "monika.hamplova@mpsv.cz": [25],
    "petrjezek@centrum.cz": [29],
    "dagmar.jarosova@mpsv.cz": [25],
    "greplova@nvf.cz": [22],
    "jan.kubat@fdv.mpsv.cz": [39],
    "petr@petrotahal.cz": [29],
    "hana.kaluzakova@mvcr.cz": [25],
    "zdenek.foltyn@mpsv.cz": [36, 24, 25],
    "marcela.benesova@mpsv.cz": [38],
    "hradecky.pavel@ujak.cz": [29, 29],
    "bezchleba@wyda.cz": [23, 29],
    "jakub.ctvrtnik@seznam.cz": [51, 31, 29],
    "pavel.vesely@wyda.cz": [29],
    "semerad.zdenek.ing@seznam.cz": [34, 23, 29],
    "valeckova@nvf.cz": [22],
    "hana.sykorova@cityofprague.cz": [25],
    "m.horvath@seznam.cz": [29],
    "lu.c@email.cz": [34, 23, 29],
    "jiri.krupka@tiscali.cz": [29],
    "veronika.marcinkova@mpsv.cz": [33, 39, 25],
    "moldrzyk@cepp.cz": [29],
    "tereza.raczova@seznam.cz": [25],
    "eva.karlikova@mvcr.cz": [25],
    "janachrz@seznam.cz": [34, 23, 29, 29],
    "karel.vit@mpsv.cz": [25],
    "michaela.svojgrova@mpsv.cz": [22, 38],
    "volfova@mpo.cz": [21, 25, 38, 28, 30],
    "dita.tondlova@mpsv.cz": [51, 50, 25, 29],
    "kristyna.chadimova@mpsv.cz": [25],
    "hynek.zofka@mo.mpsv.cz": [27, 28],
    "martina.tomova@mvcr.cz": [25],
    "tomas.pfeifer@mvcr.cz": [25],
    "zuzana.cizkova@svitavy.cz": [33],
    "zuzana.syslova@mpsv.cz": [25],
    "lucie.malikova@mvcr.cz": [25],
    "lucie.pavlova@mchcb.cz": [33],
    "pavel.skarban@cca.cz": [29, 29],
    "jan.richter@mpsv.cz": [39],
    "simik.trialis@centrum.cz": [29],
    "dana.mackova@msmt.cz": [24],
    "petra.hradecna@czechinvest.org": [25],
    "votavovara@seznam.cz": [51, 34, 29],
    "monika.zbozinkova@email.cz": [29],
    "kasparov@vse.cz": [29],
    "eva.zbornikova@mpsv.cz": [25],
    "hana.zizkova@gmail.com": [29],
    "jan.strejcek@qsi.cz": [29],
    "hana.videnska@kr-moravskoslezsky.cz": [30],
    "eva.licmanova@fdv.mpsv.cz": [39],
    "sild@euservis.cz": [29],
    "jirina.princova@kraj-lbc.cz": [30],
    "radana.kratochvilova@mpsv.cz": [36, 39, 25, 38, 28],
    "marie.formankova@mpsv.cz": [25],
    "rysavkova.v@seznam.cz": [29],
    "vit.kettner@mpsv.cz": [36, 24, 21, 25, 29],
    "ijirikovicova@seznam.cz": [29],
    "eliska.michalkova@centrum.cz": [29],
    "marketa.novotna.58@seznam.cz": [23, 29],
    "david.hebron@email.cz": [47],
    "prokopzd@seznam.cz": [29],
    "jaromir.cap@mvcr.cz": [25],
    "renatavolejnikova@seznam.cz": [51, 23, 29],
    "miroslava.webster@seznam.cz": [29],
    "marcela.pavelkova@mpsv.cz": [25, 38, 35, 28],
    "marek.vlach@czechinvest.org": [35],
    "vit.fencl@mvcr.cz": [25],
    "ronironi@email.cz": [29],
    "pavlasuchankova@seznam.cz": [23, 29, 29],
    "monika.vanzurova@mvcr.cz": [25, 38],
    "andrealaciakova@seznam.cz": [34, 29],
    "jakub.vich@czechinvest.org": [25],
    "j.jana.brezinova@seznam.cz": [29, 29],
    "pavlina.koziskova@mpsv.cz": [50, 25, 29],
    "iveta.kucerova@mpsv.cz": [25],
    "vaclav.cermak@mpsv.cz": [25, 38],
    "tereza.prichystalova@mpsv.cz": [25, 38],
    "malikova@asistencnicentrum.cz": [29],
    "leos.krecek@kraj-lbc.cz": [35],
    "josef.vosmik@centrum.cz": [22],
    "filip_brada@hotmail.com": [29],
    "hana.pisarska@volny.cz": [29],
    "kloboucnikova@nvf.cz": [22],
    "julie.radova@mpsv.cz": [25],
    "jirka.horanek@volny.cz": [29],
    "miriam.majdysova@zl.mpsv.cz": [34],
    "jan.blahusek@mpsv.cz": [25],
    "katerina.dostalova@praha.eu": [35],
    "daniela.wogurkova@gmail.com": [29],
    "mbadurova@email.cz": [22, 29],
    "michaela.frycova@mifconsult.org": [51, 34, 29],
    "vojtech.brant@seznam.cz": [29],
    "a.krabcova@tiscali.cz": [29],
    "jiri.kabelka@mpsv.cz": [39, 25, 30],
    "suchy@nvf.cz": [22],
    "eva.cerna@siemens.com": [29],
    "ludmila.kolarova@cpkp.cz": [29],
    "klara.prochazkova@msmt.cz": [36, 24],
    "david.vilham@mpsv.cz": [25],
    "ivana.jirkova@mpsv.cz": [25],
    "stanislava.pechova@mpsv.cz": [25, 32],
    "petra.klingerova@clovekvtisni.cz": [33],
    "kamila.hajkova@mpsv.cz": [25],
    "marketa.fuchsova@mpsv.cz": [39, 25, 28],
    "gawelczyk@seznam.cz": [34, 23, 29],
    "fr.dvoracek@emal.cz": [29],
    "novnos@tiscali.cz": [51, 29],
    "zdrazil@wbs.cz": [20, 29, 49],
    "jana.havigerova@uhk.cz": [29],
    "magdalena.chlupacova@mpsv.cz": [25],
    "jolana.janovska@mpsv.cz": [39, 25],
    "jirina.pipkova@mpsv.cz": [24],
    "radek.krvac@br.mpsv.cz": [23, 29],
    "lucie.rossinski@mpsv.cz": [21, 25, 28],
    "mikulas.tichacek@mpsv.cz": [25],
    "anna.dumont@mpsv.cz": [25],
    "hoskovab@msmt.cz": [36],
    "martin.kobzan@kr-zlinsky.cz": [30],
    "franek@aqe.cz": [47],
    "radek.bliznak@gmail.com": [38],
    "sykjar@volny.cz": [29],
    "barbora.renova@mpsv.cz": [25],
    "zdenka.stranska@mpsv.cz": [25, 35],
    "eva.rybarova@mpsv.cz": [39, 25],
    "poradenstvi@jihlavsko.com": [29],
    "andrea.kozuchova@gmail.com": [23, 29],
    "lada.ussarzova@ot.mpsv.cz": [27],
    "libuse.dostalova@seznam.cz": [51, 34, 23, 29, 29],
    "knedlikova@seznam.cz": [31],
    "veronika.vankova@mpsv.cz": [25],
    "milada.kropackova@mpsv.cz": [25],
    "lucie.brzakova@email.cz": [29],
    "petr.noswitz@czechinvest.org": [25],
    "roman.hones@kr-moravskoslezsky.cz": [30],
    "sedlak@i2000.cz": [30],
    "zita.prostejovska@fsv.cvut.cz": [29, 29, 29],
    "barbora.blahova@mpsv.cz": [21, 27, 28],
    "seiblova@nvf.cz": [22],
    "barbora.castkova@mvcr.cz": [25, 38],
    "ondrej.hudi@seznam.cz": [30],
    "veronika.rosolova@mpsv.cz": [25, 38, 28],
    "dytrychova@scmvd.cz": [30],
    "richardpodborsky@seznam.cz": [34, 29],
    "novy@motorpal.cz": [29],
    "kasparkova.s@seznam.cz": [29],
    "info@oroszy.cz": [34, 29],
    "milan.posmura@mpsv.cz": [39, 25],
    "kamila.vadlejchova@mpsv.cz": [50, 25, 29],
    "tyna.adamova@fdv.mpsv.cz": [39],
    "juroska@volny.cz": [34, 29],
    "coufalik@nvf.cz": [29, 29],
    "kourilov@vse.cz": [35],
    "sylvie.heidlerova@business-continuity.cz": [29],
    "sadilkova.katerina@seznam.cz": [29],
    "gambano@seznam.cz": [29],
    "ales.vondras@mpsv.cz": [21, 25],
    "milan.kvapil@mpsv.cz": [39, 25, 35],
    "martinkova@sons.cz": [33],
    "kleisnerova@lct.cz": [29],
    "pokorna@aqe.cz": [47],
    "radomil.pucalka@ol.mpsv.cz": [27, 25, 28],
    "matuliv@gmail.com": [25, 32, 29],
    "julie.hrochova@mpsv.cz": [21, 25, 28],
    "bartosova.lenka@mpo.cz": [25],
    "r.augustin@kr-olomoucky.cz": [35],
    "jana.hrazdilova@mvcr.cz": [25, 38],
    "teply@fsv.cuni.cz": [35],
    "gruka@seznam.cz": [29],
    "linda.janatova@mpsv.cz": [25],
    "alexandra.babickova@mpsv.cz": [36, 25, 38, 28],
    "jana.konstantinova@gmail.com": [22, 34, 23, 29, 49],
    "tereza.fuka@praha.eu": [35],
    "miroslavpodhajsky@seznam.cz": [29],
    "zdenkahajna@seznam.cz": [34, 23, 29],
    "frnkova@atlas.cz": [34, 29],
    "andrea.polkova@mpsv.cz": [39],
    "molik@impel.cz": [29],
    "jan.vancura@mpsv.cz": [25],
    "radka.pospisilova@mpsv.cz": [25],
    "natasadi@seznam.cz": [29],
    "alena.sirotkova@mvcr.cz": [25],
    "veronikapacesova@gmail.com": [51, 34, 23, 29],
    "pavel.vicherek@seznam.cz": [23, 29],
    "ondrej.jukl@mpsv.cz": [29],
    "petra.holubcova@pre.cz": [30],
    "tinclova.jitka@seznam.cz": [29],
    "zemanova.lenka@centrum.cz": [29],
    "miroslava.matyasova@ea-oplzz.cz": [25],
    "reitingerova@kraj-jihocesky.cz": [30],
    "jtinlova@seznam.cz": [23, 29],
    "veronika.kindlova@mpsv.cz": [25],
    "marek.jerie@mpsv.cz": [39, 25],
    "jany.ne@seznam.cz": [29],
    "tereza.belouskova@mpsv.cz": [25, 28],
    "jiri.janovsky@mvcr.cz": [38],
    "monika.ljubkova@mpsv.cz": [25],
    "lucie.pospisilova@mpsv.cz": [25],
    "jaroslava.havlickova@plzensky-kraj.cz": [35],
    "evaprochaz@seznam.cz": [34, 23, 29],
    "ladislav.vitek@plzensky-kraj.cz": [30],
    "josef.slar@mvcr.cz": [25],
    "lenka.topkova@mpsv.cz": [25],
    "houska@pef.czu.cz": [29, 29, 29],
    "martina.macurova@cpkp.cz": [51, 34, 23, 29],
    "cerna.martina@kr-ustecky.cz": [24, 35],
    "maskarincova@seznam.cz": [51, 29],
    "maunka@seznam.cz": [29],
    "t.lajza@seznam.cz": [29],
    "stepanka.juzova@mpsv.cz": [50, 25],
    "michaela.hanzlikova@mpsv.cz": [25],
    "helena.petrokova@mpsv.cz": [38],
    "petra.kottova@mpsv.cz": [21, 25],
    "zdarskavlad@seznam.cz": [29],
    "sarka.danhelova@email.cz": [29],
    "vacek.lubomir@seznam.cz": [29],
    "pavlina.janova@mpsv.cz": [27, 28],
    "eva.kalinova@mpsv.cz": [25, 38],
    "mariankova@centrum.cz": [29],
    "janka.kopecna@mpsv.cz": [25, 38],
    "vladimir.kvaca@mpsv.cz": [38],
    "eva.rathouska.grmelova@gmail.com": [29],
    "p.podivinsky@kr-olomoucky.cz": [29],
    "ivana.skrivanova@mvcr.cz": [38],
    "mseverova@seznam.cz": [29],
    "vkulhavy@gmail.com": [29],
    "l.matejickova@a-trend.cz": [29],
    "katerina.dosoudilova@gmail.com": [34, 29],
    "lenka@vse.cz": [29],
    "tereza.zahalkova@mpsv.cz": [25],
    "lenka.dvorakova@pre.cz": [30],
    "pavel.ondrak@bm.mpsv.cz": [34, 23, 29],
    "ivana.projsova@mpsv.cz": [24, 33, 39, 25, 38],
    "helena.vychova@vupsv.cz": [31],
    "katerina.hlovoskova@adminmz.cz": [31],
    "blanka.hrudkova@seznam.cz": [34, 29],
    "karel.ritschel@mvcr.cz": [25],
    "ales.kavalir@seznam.cz": [20, 29],
    "kolinova.jitka@tiscali.cz": [34, 23, 29],
    "marta.sindlarova@czechinvest.org": [25],
    "vokurkova30@seznam.cz": [20, 29],
    "magda.cabrnochova@mpsv.cz": [25],
    "jirusek@iol.cz": [29],
    "martin.vanek@mpsv.cz": [21, 25, 38],
    "miroslav.vrabel@mpsv.cz": [38],
    "lenka.fardova@seznam.cz": [22, 25, 32, 34, 23, 29],
    "kacenkahlavackova@seznam.cz": [22],
    "sakslova.v@seznam.cz": [29],
    "marketa.valova@mpsv.cz": [25],
    "kubatova.ha@seznam.cz": [29],
    "jitka.dadova@mpsv.cz": [25],
    "ladislava.vesela@mpsv.cz": [25, 38, 35, 28],
    "marketa.laube@gmail.com": [29],
    "radka.havlova@centrum.cz": [29],
    "lukas.voborsky@mpsv.cz": [25],
    "veronika.sera@mpsv.cz": [50, 25, 29, 28],
    "zdenek.drga@mpsv.cz": [39, 25, 38, 28],
    "marketa.alexova@mpsv.cz": [25],
    "michaela.nemcova@mpsv.cz": [25],
    "lenka.ruzickova@mpsv.cz": [39],
    "lenka.macickova@seznam.cz": [31],
    "cizek@kraj-jihocesky.cz": [30],
    "lenka.kozelkova@mpsv.cz": [25],
    "eva.flanderkova@mpsv.cz": [39],
    "r.vyduch@seznam.cz": [34, 29],
    "evakacanu@seznam.cz": [51, 29],
    "helena.ptakova@mpsv.cz": [25],
    "n.morochovicova@seznam.cz": [51, 34, 29],
    "jirina.shrbena@inovapro.cz": [29],
    "ilona.blazickova@ot.mpsv.cz": [27, 25, 28],
    "barbora.korinkova@mpsv.cz": [25],
    "synovcova@seznam.cz": [29, 29, 29],
    "haklova@mpo.cz": [25],
    "sykorova.eliska@email.cz": [29],
    "milenahanykova@email.cz": [29],
    "jiri.kinsky@mpsv.cz": [36, 25],
    "lenka.navratilova@cb.mpsv.cz": [27, 25, 28],
    "igor.sladek@mpsv.cz": [39],
    "josef.vacikar@plzensky-kraj.cz": [30],
    "barbora.chmelarova@mpsv.cz": [39, 25, 35],
    "volfova@krasnalipa.cz": [29],
    "bunatova.marie@email.cz": [51, 34, 23, 29],
    "karel.opocensky@nuv.cz": [29],
    "jrehacek@kpmg.cz": [25],
    "jaroslava.machova@mvcr.cz": [25],
    "ilona.jelenova@mpsv.cz": [33, 25],
    "radka.nahlovska@mpsv.cz": [21, 25],
    "dhapl@email.cz": [51, 20, 29],
    "petra.strofova@mpsv.cz": [25],
    "sapnov@autosap.cz": [30],
    "vane@dcit.cz": [29],
    "r.kottnerova@kr-olomoucky.cz": [20, 29],
    "lukas.lojda@mvcr.cz": [25],
    "kaim@icpf.cas.cz": [24],
    "marie.halatova@mpsv.cz": [25, 38],
    "musil@svazpekaru.cz": [30],
    "helena.kolibova@fvp.slu.cz": [29],
    "hana.regnerova@charita.cz": [29],
    "jaroslava.zarybnicka@mpsv.cz": [33, 25],
    "vyhnanek@nvf.cz": [22, 25],
    "radek.jiranek@mvcr.cz": [34, 29],
    "vedran.bostandzic@czechinvest.org": [25],
    "zdenka.kucerova@mpsv.cz": [25],
    "marketa.nekolova@gmail.com": [29],
    "petr.lenc@sf-poradenstvi.cz": [51, 34, 34, 29],
    "marie.blazkova@dc.mpsv.cz": [29],
    "petra.vachova@mpsv.cz": [25],
    "veronika.virtova@mpsv.cz": [25],
    "petra.altmannova@qqt.cz": [31],
    "sylvie.syrova@mpsv.cz": [25],
    "alenate@seznam.cz": [29],
    "avicom@seznam.cz": [20],
    "viera.hudecova@mpsv.cz": [25],
    "petra.francova@nros.cz": [29],
    "jitka.kovarikova@mpsv.cz": [25],
    "simona.boldi@seznam.cz": [23, 29],
    "zuzana.horkova@adminmz.cz": [31],
    "soudek@iex.cz": [29],
    "veronika.zalomova@mvcr.cz": [25, 38],
    "pouchla@nvf.cz": [22],
    "janahrda@centrum.cz": [29],
    "iva.kabelacova@fdv.mpsv.cz": [39],
    "nadezda.holmanova@vfn.cz": [22, 25, 32, 34, 23, 29],
    "blanka.myskova@mpsv.cz": [25],
    "tomasviatr@centrum.cz": [23, 29],
    "zuzanahonigova@seznam.cz": [29],
    "vojtech.smrcka@cityofprague.cz": [24],
    "kackapel@seznam.cz": [22],
    "outly@nvf.cz": [22],
    "dagmar.opravilova@fdv.mpsv.cz": [39],
    "dobsik.frantisek@cmkos.cz": [30],
    "vacek@ddalbrechtice.cz": [29],
    "iva.schindlerova@seznam.cz": [29],
    "vaja59@seznam.cz": [29],
    "ivana.harnikova@seznam.cz": [29],
    "karnikova@nvf.cz": [22],
    "lucie.sindlerova@mpsv.cz": [39],
    "marketa.dusankova@mpsv.cz": [25],
    "korinek.phdr@seznam.cz": [29],
    "trojan_martin@volny.cz": [29],
    "pavla.doubkova@email.cz": [29],
    "petr.chudej@mpsv.cz": [36, 25, 38],
    "katerina.lisnerova@mvcr.cz": [25],
    "zimova.dostalova@seznam.cz": [23, 29],
    "vladimira.leva@psv.cz": [25],
    "petra.hlavackova@mpsv.cz": [25],
    "vsouckova@volny.cz": [29],
    "lucie.vondrova@mpsv.cz": [25],
    "jan.jelinek@mpsv.cz": [25],
    "zounkovaz@seznam.cz": [34, 23, 29],
    "marketa.pechouckova@mpsv.cz": [25],
    "katerina.spirkova@mpsv.cz": [25],
    "miloslav.patek@mpsv.cz": [25],
    "ludmila.noskova@qqt.cz": [31],
    "krharries@gmail.com": [31, 34, 29],
    "lucie.janova@mpsv.cz": [24, 21, 25, 28],
    "zuzana.bednarova@cityofprague.cz": [51, 34, 23, 29, 29],
    "petr.janous@mvcr.cz": [25],
    "z.jarosova@gmail.com": [34, 29],
    "tamara.brozik@seznam.cz": [31],
    "konzult@centrum.cz": [29],
    "lukas.krivka@mvcr.cz": [25],
    "jitkajirsova@seznam.cz": [34, 23, 29],
    "martena@email.cz": [29],
    "lenka.murinova@centrum.cz": [29],
    "office@planb.cz": [34, 23, 29],
    "martin.sycha@msmt.cz": [35],
    "michaela.jachymova@pa.mpsv.cz": [27, 28],
    "andrea_gerstnerova@yahoo.fr": [29],
    "jana.slukova@mpsv.cz": [27, 25, 28],
    "veronika.dankova@mpsv.cz": [25, 38],
    "ivana.olivova@gmail.com": [29],
    "jan.kejzlar@centrum.cz": [29],
    "jchrtkova@seznam.cz": [39],
    "zdenka.cibulkova@cl.mpsv.cz": [34, 23, 29, 29],
    "marie.kalabova@seznam.cz": [29],
    "iva.sotolarova@mpsv.cz": [21, 25, 23],
    "irena.berankova@centrum.cz": [29],
    "bohum@email.cz": [29],
    "vaclav.lintymer@mpsv.cz": [50, 33, 39, 25, 38, 29],
    "marina.landova@mpsv.cz": [24, 25, 35],
    "ivana.javurkova@mpsv.cz": [25],
    "helena.slivkova@naep.cz": [29, 29],
    "josef.pitner@bm.mpsv.cz": [34, 23, 29],
    "dusan.jelinek@agsynerko.cz": [29],
    "jitka.machackova@lsg.cz": [29],
    "bronislava.lobodasova@mpsv.cz": [39],
    "mirka.holanova@gmail.com": [29, 29],
    "vera.kantorova@mpsv.cz": [25],
    "zora.skurcakova@mvcr.cz": [25],
    "soudek@iol.cz": [29],
    "vbullova@seznam.cz": [29],
    "ilona.volkova@mpsv.cz": [25],
    "tereza.pavlikova@mpsv.cz": [25],
    "jana.jirku@mpsv.cz": [39, 25],
    "alena.habltova@mpsv.cz": [24, 25, 30],
    "lenka.poduskova@mpsv.cz": [25],
    "blanka.ledvinkova@mvcr.cz": [25],
    "ondrej.papuga@ot.mpsv.cz": [21, 27, 25, 28],
    "vlasta.vachova@klikni.cz": [29],
    "d.benakova@centrum.cz": [47],
    "jan.jindra@mpsv.cz": [25],
    "klara.zubova@czechinvest.org": [35],
    "jana.novakova@pardubickykraj.cz": [29],
    "radoslav.lukovic@mvcr.cz": [25],
    "emil.machalek@seznam.cz": [29],
    "petr.hlousek@kraj-lbc.cz": [30],
    "miroslav.huml@mpsv.cz": [25],
    "daniela.kyselova@mpsv.cz": [25],
    "naus@kr-s.cz": [30],
    "kuzelkova@gmail.com": [22, 25, 32],
    "svetlana.navarova@mpsv.cz": [25],
    "ondrej.daniel@gmail.com": [35],
    "jan.janatka@everesta.cz": [29],
    "iva.tuzinska@msmt.cz": [36],
    "monika.kocabkova@mpsv.cz": [25],
    "hradecky@nadeje.cz": [29],
    "aneta.jezova@fdv.mpsv.cz": [39],
    "jana.stavinohova@mpsv.cz": [25],
    "zuzana.kodym@seznam.cz": [29],
    "petra.francova@mpsv.cz": [20],
    "frycova.lucie@seznam.cz": [29],
    "petruskova.alena@seznam.cz": [23, 29],
    "miroslav.kohout@mvcr.cz": [25],
    "petr.kaplan@mpsv.cz": [35],
    "jana.cvikyrova@mvcr.cz": [38],
    "jaromir.votruba@mpsv.cz": [25, 38, 28],
    "lucie.kucerova@mvcr.cz": [50, 25],
    "edita@kozinova.com": [29],
    "jakubverner@seznam.cz": [29],
    "potluka@ireas.cz": [34, 29],
    "andrej.gorcos@mpsv.cz": [25],
    "marcel.ditt.64@seznam.cz": [22, 29],
    "kveta.sekyrova@centrum.cz": [22],
    "matesova@matesova.cz": [29],
    "lauermann@email.cz": [51, 29, 49],
    "musilova@doksy.com": [29],
    "pospisilova@sons.cz": [33],
    "lukas.cenek@czechinvest.org": [25],
    "michaela.kocnerova@mvcr.cz": [25, 38],
    "magda.simonova@mvcr.cz": [38],
    "v.sterbova@eurovision.cz": [29],
    "veronika.bozovska@mpsv.cz": [39],
    "michalickova@seznam.cz": [29],
    "martin.dolezal@mpsv.cz": [36],
    "vastyl@mpo.cz": [38],
    "hvezda@tmcentrum.cz": [29],
    "vit.stengl@mvcr.cz": [25, 38],
    "terezabrozikova@seznam.cz": [31],
    "1781961@seznam.cz": [23, 29],
    "petula.nemi@seznam.cz": [25],
    "z.lastovkova@seznam.cz": [25],
    "k.ulikova@centrum.cz": [29],
    "barbora.zelenkova@mvcr.cz": [25, 38],
    "pavel.cihak@email.cz": [29],
}

MANAGERS = {
    "svatava.skantova@mpsv.cz": [20],
    "iva.sotolarova@mpsv.cz": [29, 50],
    "jiri.kabelka@mpsv.cz": [14, 35],
    "vit.kettner@mpsv.cz": [24, 25],
    "monika.ljubkova@mpsv.cz": [51],
    "ivana.jirkova@mpsv.cz": [7],
    "tomas.hobza@mpsv.cz": [27, 28],
    "vera.nouzova@mpsv.cz": [6, 48],
    "dita.tondlova@mpsv.cz": [5],
    "katerina.zivotska@mpsv.cz": [21],
    "adela.purschova@mpsv.cz": [19, 46],
    "petra.hlavackova@mpsv.cz": [8],
    "marketa.alexova@mpsv.cz": [13, 37],
    "petra.kottova@mpsv.cz": [45, 49],
    "pavlina.koziskova@mpsv.cz": [22, 23, 47],
    "anna.burjankova@mpsv.cz": [31, 32, 33, 34],
    "tereza.prichystalova@mpsv.cz": [39],
    "helena.ptakova@mpsv.cz": [52],
    "lada.vyhnankova@mpsv.cz": [12],
    "jan.blahusek@mpsv.cz": [26],
    "kohout@mpo.cz": [9, 10, 11, 30],
    "anna.ficova@mpsv.cz": [2, 3, 4],
    "zdenek.foltyn@mpsv.cz": [36, 38],

    # COEX
    "frantisek.salava@coex.cz": [55],
    "martin.kubat@coex.cz": [55],
    "vasek.chalupnicek@gmail.com": [55]
}


def set_membership(sender, instance, created, **kwargs):
    """
        after create user account (registration, admin, ...)
    """

    if not created:
        return

    data = [
        [NODE_USER_ROLE_MANAGER, MANAGERS, True],
        [NODE_USER_ROLE_MEMBER, MEMBERS, False],
    ]

    for role, users, is_responsible in data:
        for node_pk in users.get(instance.email.lower(), []):
            try:
                node = Node.objects.get(pk=node_pk)
                obj, created = node.node_users.get_or_create(
                    user=instance,
                    defaults={
                        "role": role,
                        "is_responsible": is_responsible
                    }
                )

            except Exception, e:
                logging.error("Automatic create membership failed: %s" % repr({
                    "user_pk": instance.pk,
                    "username": instance.username,
                    "role": role,
                    "node": node_pk,
                    "is_responsible": is_responsible,
                    "error": e
                }))

            else:
                logging.info("Automatic create membership: %s" % repr({
                    "user_pk": instance.pk,
                    "username": instance.username,
                    "role": role,
                    "is_responsible": is_responsible,
                    "node": node_pk
                }))
